### ISSUE TITLE
STA9750 SethKauf MiniProject #00

### ISSUE THREAD

**Issue by SethKauf** [SethKauf/STA9750-2024-FALL#1]
Hi @michaelweylandt !

I've created my STA9750 website - check it out!

 https://SethKauf.github.io/STA9750-2024-FALL

**Comment by michaelweylandt** [comment]
Thanks @SethKauf !

Peer Feedback:

- @bleuuuz
- @Chloe384
- @matata668

Please a look at the website associated with this GitHub repo
and provide some peer feedback to @SethKauf.

Website URL should be: https://SethKauf.github.io/STA9750-2024-FALL/

If that link doesn't work, please check out the GitHub profile for @SethKauf and
see if you can help them get it working.

At a minimum, please note:

1. Something you like about the submission.
2. A suggestion on how to improve it.

Feel free to link to other repos, the course documentation, or other useful
examples.

This submission is ungraded, so there's you don't need to provide
a numerical score.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by Chloe384** [comment]
I like the theme of your website. I would suggest adding more content to your page. You could introduce yourself and give some information about your major, hobbies or academic experience.

**Comment by bleuuuz** [comment]
Hi Seth, I think the color contrast on your website is nice! Maybe you could include more background information about yourself; if you want to remain anonymous, you could have a pen name. Thanks for sharing!

**Comment by SethKauf** [comment]
Thanks for the feedback everyone, I recently pushed some changes/updated details to the index file, I think it's taking some time to render through GitHub, though.

**Comment by matata668** [comment]
Hi @SethKauf,

I really like your website, it has my attention at once, and also looks very clean. great use of pictures and links in your website. Maybe now you can create them as tabs that way you could create a drop down menu for formulas that you hvae learned and that might even help fellow students taking that class :)
