### ISSUE TITLE
STA9750 SethKauf MiniProject #01

### ISSUE THREAD

**Issue by SethKauf** [SethKauf/STA9750-2024-FALL#3]
Hi @michaelweylandt!

I've uploaded my work for MiniProject #01 - check it out!

https://SethKauf.github.io/STA9750-2024-FALL/mp01.html

**Comment by michaelweylandt** [comment]
Thanks @SethKauf !

Peer Feedback:

- @nikitagtm
- @CristelKZuniga
- @plnrbrt
- @greazyz

It is now time for the peer feedback round for Mini-Project #01. Please
review @SethKauf's submission for this mini-project and provide peer feedback.

Using the rubric at https://michael-weylandt.com/STA9750/miniprojects/mini01.html#rubric,
please grade their submission out of a total of 50 points.

For each of the five categories, please give them a separate score and provide
a total (sum) score across the entire assignment. Feel free to assign extra
credit if you feel it is warranted (following the rubric).

If you give a score of less than 5 for any category, please provide a suggestion
for improvement. (You can also give suggestions for any element they did well -
more feedback is always great!)

As you go through this peer feedback exercise, think about what you particularly
like about this submission and how you can incorporate that approach in your future
work. If something is particularly insightful or creative, give some kudos!

Evaluators: This should take you around 15 minutes per peer feedback. You are
not required to engage in substantial back-and-forth with @SethKauf, but you are of course
welcome to initiate a discussion.

@SethKauf: please engage fully with your peers. They are here to help you!

Submission URL should be: https://SethKauf.github.io/STA9750-2024-FALL/mp01.html

Feel free to link to other repos, the course documentation, or other useful
examples.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by nikitagtm** [comment]
Congratulations Sethkauf for completing your MiniProject#1. 
**What I Liked:**
Written Communication: Clear and effective, with good flow throughout the project.
Project Skeleton: Well-structured, covering all necessary components.
Code Quality: Efficient and well-organized, demonstrating a strong understanding of data manipulation.
Data Preparation: Thorough and accurate, ensuring reliable analysis.

**Suggestions for Improvement:**
Formatting: Including an efficient introduction, conclusion or key points of the project would make the project more comprehensive and clearer in terms of purpose and findings.
Package Installation: In Task 3.3, you install a package (stringr) in the middle of your code. It would be more efficient to include all package installations at the beginning of the project. This makes it easier for someone reviewing your code to see which packages are necessary upfront and ensures a smoother workflow without interruptions for installations.

Ratings:
Written Communication: 8/10
Project Skeleton: 9/10
Formatting & Display: 10/10
Code Quality: 9/10
Data Preparation: 10/10
Total Score: 46/50

Thanks,
Nikita

**Comment by charles-ramirez** [comment]
Hi,@CristelKZuniga @plnrbrt @greazyz,

This is just a reminder that your peer review is due today at 11:45 pm.

**Comment by greazyz** [comment]
Hi SethKauf, 

I like how everything was aligned with the assignment. The notes within the R code are helpful in what I am looking at and what you are doing. I think you are missing a conclusion at the end though! 

Written Communication: 7
	There weren’t any text guiding the audience at what they were lookijng at. I think you can add sentences throughout the site to explain the steps and how they are linked together. 
Project Skeleton: 10
Formatting & Display: 8
	The graphs were a little overwhelming with no text guiding the audience along but the plot graph was informative and creative! 
Code Quality: 10

Score: 45/50

**Comment by plnrbrt** [comment]
Hi @SethKauf!
Thank you so much for sharing your mini-project!
Here are my comments below:
Written Communication: 6/10
I like how you clearly separated each step of your analysis but I feel like it is lacking of context and description. I would have been nice maybe to add as hyperlink the data sources in a small explanatory text at the beginning of the analysis to explain where you got the data from. Also, a phrase to highlight your findings would have been nice as well as a conclusion to your analysis.
Project Skeleton: 10/10
Everything flows and all the instructors instructions are answered.
Formatting & Display: 8/10 + 1 extra credit -> 9/10
I love the graph (+1 credit)! Great job on that one, wished I had the idea myself! However for the rest of the code, would have been nice to have it better presented in a nice table.
Code Quality: 8/10
Code is good and well written. I am just missing some basic comments and context for each code to understand better why you are using those function and what is the code demonstrating.
Data Preparation: 10/10
Total: 43/50

**Comment by CristelKZuniga** [comment]
Hello @SethKauf ,

I'm happy to see the project shared with the group! I have a few comments that I hope will help you improve and identify some opportunity areas for the next mini-project."

-Written Communication (7)
I think you could have expanded more on the tasks requested. Next time, I suggest explaining and providing a more detailed analysis of the results, so the answers make more sense to the reader, who might not be familiar with the subject.

-Project Skeleton (9)
Most activities are effectively completed and structured. Except I couldn’t find a conclusion of the project. 

- Formatting & Display (8):
The tables are well-formatted.  For next time, I’d recommend answering right next to the question before showing the code, also to use maybe a different typography to enhance your project and highlight where are the results of your analysis. 

- Code Quality (9):
The code is clear and executes properly. I would suggest adding more comments to make it easier for the reader to understand what the code is doing.

-Data Preparation (10)

Total: 43/50

Thank you!
