### ISSUE TITLE
ISSUE FOR MP03 PEER FEEDBACK - INSTRUCTOR OPENED

### ISSUE THREAD

**Issue by michaelweylandt** [SethKauf/STA9750-2024-FALL#5]
Thanks @SethKauf !

Peer Feedback:

- @Haina0
- @Malexandra-Jerez
- @Will-Peters
- @Gautam-1-R

It is now time for the peer feedback round for Mini-Project 03. Please
review @SethKauf's submission for this mini-project and provide peer feedback.

Using the rubric at https://michael-weylandt.com/STA9750/miniprojects/mini03.html#rubric,
please grade their submission out of a total of 50 points. Note that this
rubric is slightly different than that used for Mini-Projects 01 and 02.

For each of the five categories, please give them a separate score and provide
a total (sum) score across the entire assignment. Feel free to assign extra
credit if you feel it is warranted (following the rubric).

If you give a score of less than 5 for any category, please provide a suggestion
for improvement. (You can also give suggestions for any element they did well -
more feedback is always great!)

As you go through this peer feedback exercise, think about what you particularly
like about this submission and how you can incorporate that approach in your future
work. If something is particularly insightful or creative, give some kudos!

Evaluators: This should take you around 15 minutes per peer feedback. You are
not required to engage in substantial back-and-forth with @SethKauf, but you are of course
welcome to initiate a discussion.

@SethKauf: please engage fully with your peers. They are here to help you!

Submission URL should be: https://SethKauf.github.io/STA9750-2024-FALL/mp03.html

Feel free to link to other repos, the course documentation, or other useful
examples.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by SethKauf** [comment]
Hi @michaelweylandt!

Thank you for opening the issue! My project is available at link you provided.

https://sethkauf.github.io/STA9750-2024-FALL/mp03.html

**Comment by Gautam-1-R** [comment]
hi @SethKauf 

Great work on the mini project.
Written Communication: 8/10
The report is clear, well-organized, and logical. Adding a bit more context around each section would help readers understand the purpose of each analysis step.

Project Structure: 9/10
The project structure is great and meets all the requirements. At least a brief introduction or conclusion would add to the overall narrative.

Formatting & Display: 8/10
The visuals are clear, visually appealing, and well-captioned. Including summary tables of the findings would add to the graphs and give more intuition into the findings.

Code Quality: 9/10
The code is well-structured, neat, and easy to read. A few comments to explain would be nice to make the logic easily understood by others.

Data Preparation: 10/10
Very good data preparation, indicating attention to detail and completeness.

Total: 44/50

**Comment by Haina0** [comment]
Hi @SethKauf - Here’s my feedback on your Mini-Project #03:

Written Communication: 8/10
Your project is well-documented, and the introductory section provides a good start. Perhaps, adding a concluding section to summarize findings and address the "fairness" aspect of different ECV schemes would round out the project nicely.

Project Skeleton: 9/10
You completed the tasks outlined in the instructions. Additionally, the comparisons between ECV allocation methods were present but could benefit from deeper analysis and discussion of the outcomes.

Formatting and Display: 9/10
Your visualizations are well-constructed and easy to read. The use of color to distinguish parties on the maps was effective, and the layout of your plots is clean. Consistent use of headings and some additional descriptions for graphs and tables would help the flow of the document. 

Code Quality: 10/10
Your code is clear, concise, and well-documented with comments. It demonstrates your understanding of the tools and methods used. 

Data Preparation: 10/10
Your data preparation is thorough, and you successfully downloaded and processed the necessary datasets. It’s evident that you paid attention to detail in cleaning and preparing the data for analysis. 

Total Score: 46/50

**Comment by SethKauf** [comment]
Hi @Haina0 ,

Thank you for your comment - could you double check Task 6, for the animated map, please? It should be there and seems to be when I go to the site myself.

![image](https://github.com/user-attachments/assets/049ef0f6-1ea2-4bf7-bc88-59a667d68b86)

Please let me know if you're still not seeing it and I'll push a fix when I'm home.

Thanks.

**Comment by Haina0** [comment]
Apologies for the misunderstanding, you are correct. I've updated my feedback to reflect that. Thank you.

**Comment by Will-Peters** [comment]
Hi Seth, 

Written Communication: 9/10
Good introduction helps to set the tone provides a good start. However I would add a bit more callout particularly in the finale how the separation between each voting strategy operated.

Project Skeleton: 9/10
More discussion and analysis on the Questions would have been useful

Formatting and Display: 9/10
I would recommend adding some separation of each strategy before aggregating into one view however otherwise really good work.

Code Quality: 9/10 
Code is clear and well presented, however for the district dates don't understand how you extracted it maybe add a bit more explanation around that

Data Preparation: 10/10
Your data preparation is thorough, and you successfully downloaded and processed the necessary datasets. It’s evident that you paid attention to detail in cleaning and preparing the data for analysis.

Total Score: 46/50
